server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: micro-users
          uri: lb://users # same name that application name of the microservice in its file.yml
          predicates:
            - Path=/users/**
        - id: micro-pizzaRead
          uri: lb://pizzaRead
          predicates:
            - Path=/pizzaRead/**
        - id: micro-pizzaWrite
          uri: lb://pizzaWrite
          predicates:
            - Path=/pizzaWrite/**