# application.yml configuration for Config Server CLIENT
spring:
  application:
    name: pizzaWrite  # same name that config server have for the yml file
  cloud:
    config:
      uri: http://localhost:8888  # Where config server is deployed
