# application.yml configuration for Config Server CLIENT
spring:
  application:
    name: pizzaRead
  cloud:
    config:
      uri: http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher