# application.yml configuration for Config Server
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: classpath:/configuration # path where there are the configuration files for client
  profiles:
    active: native